from fpdf import FPDF
import datetime
import re

def sanitize_pdf_text(text: str) -> str:
    """
    Sanitizes input text for FPDF Latin-1 font compatibility by mapping emojis
    to readable text tags and filtering unsupported unicode characters.
    """
    if not text:
        return ""
    
    # Map common emojis to readable text tags
    emoji_map = {
        "🛰️": "[SATELLITE]", "🛰": "[SATELLITE]",
        "⛈️": "[CLOUDBURST]", "⛈": "[CLOUDBURST]",
        "🌫️": "[FOG]", "🌫": "[FOG]",
        "🔴": "[HALT]", "🟢": "[GREEN LIGHT]", "🟡": "[CAUTION]",
        "🎬": "[CINEMA]", "📑": "[DISPATCH]", "📍": "[LOCATION]",
        "🌤️": "[CLEAR]", "🌧️": "[RAIN]", "⚡": "[FLASH]",
        "📥": "[DOWNLOAD]", "📋": "[SCENE]", "📜": "[LOG]",
        "🏎️": "[CAR CHASE]", "🌊": "[BEACH]", "🏔️": "[MOUNTAIN]", "☀️": "[SUN]",
        "🧠": "[BRAIN]", "🔬": "[PHYSICS]", "🎛️": "[PARAMS]", "🌐": "[GLOBAL]"
    }
    
    clean_str = str(text)
    for emoji, replacement in emoji_map.items():
        clean_str = clean_str.replace(emoji, replacement)
    
    # Replace non-latin-1 characters safely
    return clean_str.encode('latin-1', 'replace').decode('latin-1').replace('?', '')

class CrisisShiftPDF(FPDF):
    def header(self):
        self.set_fill_color(18, 18, 24)
        self.rect(0, 0, 210, 297, 'F')  # Dark obsidian background
        
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(255, 159, 0)  # Electric Amber
        self.cell(0, 10, 'CRISISSHIFT OS | AUTONOMOUS CINEMA DISPATCH', border=False, new_x="LMARGIN", new_y="NEXT", align='L')
        
        self.set_draw_color(255, 159, 0)
        self.set_line_width(0.8)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 9)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Gemini 3.8 Swarm Engine', align='C')

def generate_pdf_report(
    title: str,
    location_name: str,
    weather_mode: str,
    stunt_status: str,
    blueprint_text: str
) -> bytes:
    """
    Generates a clean PDF document byte stream for user download with 100% Unicode safety.
    """
    pdf = CrisisShiftPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Sanitize all header parameters
    clean_title = sanitize_pdf_text(title)
    clean_loc = sanitize_pdf_text(location_name)
    clean_weather = sanitize_pdf_text(weather_mode)
    clean_status = sanitize_pdf_text(stunt_status)
    
    # Metadata Box
    pdf.set_fill_color(25, 25, 34)
    pdf.rect(10, 25, 190, 32, 'F')
    
    pdf.set_y(28)
    pdf.set_x(15)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 6, f"LOCATION: {clean_loc}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_x(15)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(255, 208, 0)
    pdf.cell(0, 6, f"WEATHER FEED: {clean_weather}  |  STATUS: {clean_status}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_x(15)
    pdf.set_text_color(148, 163, 184)
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 6, f"TIMESTAMP: {ts}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(255, 159, 0)
    pdf.cell(0, 8, clean_title.upper(), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    # Report Body Text
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(241, 245, 249)
    
    lines = blueprint_text.split('\n')
    for line in lines:
        clean_line = sanitize_pdf_text(line)
        if not clean_line.strip():
            pdf.ln(3)
            continue
            
        if clean_line.startswith('#'):
            pdf.set_font('Helvetica', 'B', 11)
            pdf.set_text_color(255, 159, 0)
            pdf.multi_cell(190, 6, clean_line.replace('#', '').strip())
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(241, 245, 249)
        else:
            pdf.multi_cell(190, 5, clean_line)
            
    return bytes(pdf.output())
